package dbmetropolis;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

import javax.swing.table.AbstractTableModel;

/**
 * Custom table model created for this
 * project. It is used to save 3 
 * columns, metropolis (string)
 * continent (string) and population (int)
 * @author User Tornike onoprishvili
 *
 */
public class MyTableModel extends AbstractTableModel implements IMyTableModel {
	
	/**
	 * Main data storage.
	 */
	List<Row> data = new ArrayList<Row>();
	
	public MyTableModel() {
		
	}
	
	/**
	 * Creates a model fom SQL resultset.
	 * @param rs ResultSet generated by using SQLQuery
	 * @throws SQLException is Resultset is in any way malformed, exception is thrown. 
	 */
	public MyTableModel(ResultSet rs) throws SQLException {
      while (rs.next()) {
          String metropolis = rs.getString("metropolis");
          String continent = rs.getString("continent");
          Integer population = rs.getInt("population");
          data.add(new Row(metropolis, continent, population));
      }
	}

	@Override
	public int getColumnCount() {
		return COLUMN_COUNT;
	}

	@Override
	public int getRowCount() {
		return data.size();
	}

	@Override
	public Object getValueAt(int rowIndex, int columnIndex) {
		return data.get(rowIndex);
	}

	@Override
	public Row getRowAt(int idx) {
		return data.get(idx);
	}

	@Override
	public void addRow(Row r) {
		data.add(r);
	}

	@Override
	public void setRowAt(int idx, Row r) {
		data.set(idx, r);
	}
}
